# Generated by Django 4.1.4 on 2022-12-25 22:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', tinymce.models.HTMLField(max_length=1000, verbose_name='Description')),
            ],
            options={
                'verbose_name': "Yurii Palamarchuk's Introduction",
                'verbose_name_plural': "Yurii Palamarchuk's Introduction",
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('preview', models.ImageField(upload_to='projects/previews', verbose_name='Preview image')),
                ('github', models.URLField(blank=True, verbose_name='GitHub link (leave blank if none)')),
                ('link', models.URLField(verbose_name='Link to demo')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
