# Generated by Django 4.1.4 on 2022-12-25 22:42

from django.db import migrations, models
import portfolio.storage


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='picture',
            field=models.ImageField(null=True, upload_to='introduction/', verbose_name='Picture'),
        ),
        migrations.AddField(
            model_name='introduction',
            name='resume',
            field=models.FileField(null=True, storage=portfolio.storage.OverwriteStorage(), upload_to='introduction/'),
        ),
    ]
