# Generated by Django 4.1.4 on 2022-12-25 23:14

from django.db import migrations, models
import portfolio.storage
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_introduction_picture_introduction_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='description',
            field=tinymce.models.HTMLField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='picture',
            field=models.ImageField(upload_to='introduction/', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='resume',
            field=models.FileField(storage=portfolio.storage.OverwriteStorage(), upload_to='introduction/'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
